FROM alpine:3.19.1
RUN apk update && apk add nginx && rm -rf /var/cache/apk/*
RUN addgroup -g 1000 noob && adduser -D -u 1000 -G noob noob
RUN chown noob:noob -R /var/lib/nginx /var/log/nginx /run/nginx
USER noob
CMD nginx -g 'daemon off;'