version: '3.9'

services:
  server:
    container_name: server
    image: nginx_server
    build:
      context: .
      dockerfile: dockerfile
    networks:
      - nginx_server
    ports:
      - '8080:8080'
    volumes:
      - ./html:/var/www/html
      - ./confing:/etc/nginx

networks:
  nginx_server: