version: '3.9'

services:
  server:
    container_name: server
    image: nginxserver
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./html:/var/www/html
      - ./confing/nginx.conf:/etc/nginx/nginx.conf